from neko_sdk.neko_framework_NG.data.supportdb.support_utf_im_lmdb import neko_random_support_fetcher

import os.path

import torch

from neko_sdk.neko_framework_NG.UAE.neko_modwrapper_agent import neko_module_wrapping_agent as ama
from neko_sdk.neko_framework_NG.workspace import neko_workspace, neko_environment
from neko_sdk.cfgtool.argsparse import neko_get_arg

# load from precached images and fetch with utf
# More versions will come if needed
class abstract_sideinfo_index_agent(ama):

    # --- and a utf may rabbit down to different representations
    # but no matter--- plabels are generated by translating sideinfo utf on the fly, on the head.
    # note this one instance do not rabbit. But heck you can if you want to.
    PARAM_mod_path="mod_path"
    INPUT_utf="utf";
    INPUT_tdict="tdict";
    # usually, it does not alter tdict---
    # but if weird things happen, it can ---
    # say a character does not have proto at all---
    # then it will be removed from tdict---
    # or there are some subvarianting (say a-> [a_italic, a_normal], then there will be more)
    # what matters is --- always refrain to do things with meta tdict instead of the global tdict

    OUTPUT_sideinfo="sideinfo";
    OUTPUT_sideinfo_utf="sideinfo_utf"; # not all in the utf will be hit by sideinfo
    OUTPUT_sideinfo_tdict = "sideinfo_tdict";  # not all in the utf will be hit by sideinfo


    def set_mod_io(this, iocvt_dict, modcvt_dict):
        this.utf = this.register_input(this.INPUT_utf, iocvt_dict);
        this.tdict = this.register_input(this.INPUT_tdict, iocvt_dict);

        this.sideinfo = this.register_output(this.OUTPUT_sideinfo, iocvt_dict);
        this.sideinfo_tdict = this.register_output(this.OUTPUT_sideinfo_tdict, iocvt_dict);
        this.sideinfo_utf = this.register_output(this.OUTPUT_sideinfo_utf, iocvt_dict);
        pass;


    @classmethod
    def get_agtcfg(cls,
                   utf, tdict,
                   sideinfo, sideinfo_utf, sideinfo_tdict,
                   mod_path
                   ):
        return {"agent": cls, "params": {
            "iocvt_dict": {cls.INPUT_utf: utf,cls.INPUT_tdict:tdict, cls.OUTPUT_sideinfo: sideinfo, cls.OUTPUT_sideinfo_utf: sideinfo_utf, cls.OUTPUT_sideinfo_tdict: sideinfo_tdict},
            cls.PARAM_mod_path: mod_path,  "modcvt_dict": {}}}

